branches:
  - 'main'
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: 'conventionalcommits'
  - - '@semantic-release/release-notes-generator'
    - preset: 'conventionalcommits'
  - - '@semantic-release/changelog'
    - changelogFile: 'CHANGELOG.md'
  - '@semantic-release/npm'
  - - '@semantic-release/git'
    - assets:
      - 'CHANGELOG.md'
      - 'package.json'
      - 'pnpm-lock.yaml'
      message: 'chore(release): ${nextRelease.version} [skip ci]'
  - '@semantic-release/github'
